import { Dimensions, StyleSheet } from 'react-native';

const CreateStyle = StyleSheet.create({
  container: {
    alignItems: 'center',
    backgroundColor: '#f7f7f7',
    padding: 20,
    height: Dimensions.get('window').height * 1.1,
  },
  title: {
    fontSize: 36,
    marginBottom: -2,
    fontFamily: "Pac",
    color: '#fff',
  },
  header: {
    marginTop: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    paddingVertical: 10,
  },
  mapContainer: {
    padding: 5,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    marginTop: 5,
    borderBottomEndRadius: 15,
    borderBottomStartRadius: 15,
    width: '104%',
    alignItems: 'center',
  },
  description: {
    fontSize: 14,
    color: '#fff',
    fontFamily: "Kan",
    textAlign: 'center',
    paddingHorizontal: 30,
    lineHeight: 18,
  },
  map: {
    width: Dimensions.get('window').width * 0.9359,
    height: 230,
    marginTop: 5,
  },
  input: {
    height: 40,
    borderColor: 'rgba(0, 0, 0, .7)',
    borderWidth: 1,
    marginVertical: 7,
    paddingHorizontal: 10,
    width: '100%',
    paddingRight: 73,
    borderRadius: 5,
    fontFamily: 'Kan',
  },
  loadingText: {
    fontSize: 18,
    color: '#fff',
    marginTop: 20,
    fontFamily: "Pac",
  },
  nextButton: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 0,
    alignItems: 'center',
    justifyContent: "space-between",
    marginTop: 10,
    padding: 7,
    paddingHorizontal: 19,
  },
  nextButtonText: {
    color: '#000',
    fontSize: 18,
    marginRight: 5,
    fontFamily: "Kan",
  },
  text: {
    fontFamily: "Kan",
    letterSpacing: 1,
    color: '#000',
  },
  text2: {
    fontFamily: "Kan",
    letterSpacing: 1,
    color: '#000',
    top: 20,
    right: 30,
  },
  hr1: {
    height: 31,
    width: 1,
    backgroundColor: "#000",
    marginHorizontal: 18,
    shadowColor: 'rgba(240, 240, 240, 1)',
    shadowOffset: { width: 8, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 0,
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: "flex-end",
    alignItems: "center",
    width: 300,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  submitButton: {
    padding: 1,
    paddingHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
    right: 65,
    borderLeftWidth: 1,
  },
  viewPager: {
    flex: 1,
  },
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeContainer: { // New style for the time selection container
    padding: 7,
    backgroundColor: '#fff',
    borderTopStartRadius: 15,
    borderTopEndRadius: 15,
    width: '104%',
    alignItems: 'center',
    marginTop: 10,
  },
  timeText: {
    fontSize: 20,
    fontFamily: 'Kan',
    marginBottom: 15,
    color: '#000',
  },
  timeInput: {
    height: 40,
    borderColor: 'rgba(0, 0, 0, .7)',
    borderWidth: 1,
    paddingHorizontal: 10,
    width: '90%',
    borderRadius: 10,
    marginBottom: 10,
  },
  timeSubmitButton: {
    backgroundColor: '#FF7E5F',
    padding: 10,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '90%',
  },
  timeSubmitButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  picker: {
    height: 50,
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 10,
    marginVertical: 10,
    paddingHorizontal: 10,
  },
  calendarButton: { 
    backgroundColor: '#FF7E5F',
    borderRadius: 10,
    marginVertical: 5,
  },
  calendarButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  timeDigitsContainer: {
    flexDirection: 'row',
  },
  timeDigit: {
  },
  timeDigitText: {
    fontSize: 25,
    fontFamily: 'Kan',
  },
  row: {
    flexDirection: 'row',
    justifyContent: "space-between",
    width: 320,
  },
  timeText: {
    fontSize: 15,
    right: 70,
    bottom: 10,
    fontFamily: "Pac"
  },
  inputName: {
    fontSize: 15,
    backgroundColor: '#fff',
    borderRadius: 5,
    padding:5,
    paddingHorizontal: 10,
    fontFamily: 'Kan',
    width: '100%',
    letterSpacing: 1,
    borderWidth: 1,
  },
  button: {
    backgroundColor: '#fff',
    width: 370,
    height: 40,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 15,

    //shadows 
    shadowColor: 'rgba(250, 250, 250, 1)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 5,
  },
  buttonText: {
    fontFamily: "Pac",
    fontSize: 20,
  }
});

export default CreateStyle;
