import { Dimensions, StyleSheet } from 'react-native';

const CreateStyle = StyleSheet.create({
  container: {
    height: Dimensions.get('window').height * 1.05,
    paddingTop: 100,
  },
  text: {
    fontSize: 17,
    color: '#ccc',
    fontFamily: 'Kan',
    textAlign: 'center',
    marginVertical: 10,
    letterSpacing: 1.5,
  },
  mapContainer: {
    height: 130,
    borderWidth: 1,
    borderColor: "#222",
    backgroundColor: "#353535",
    padding: 5,
    borderRadius: 20,
    width: 390,
    left: 10,
    marginTop: 10,
  },
  mapContainer2: {
    height: 290,
    backgroundColor: "#222",
    padding: 5,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#353535",
  },
  map: {
    width: '97%',
    height: '100%',
    borderRadius: 10,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 15,
    paddingHorizontal: 20,
  },
  input: {
    height: 40,
    left: -18,
    width: 320,
    backgroundColor: '#222',
    borderRadius: 10,
    color: '#fff',
    borderWidth: 2,
    borderColor: "#555",
    paddingHorizontal: 10,
    fontFamily: 'Kan',
    letterSpacing: 1.2,
  },
  submitButton: {
    backgroundColor: '#333',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    left: -10,
    borderWidth: 2,
    borderColor: "#555",
  },
  inputName: {
    height: 40,
    width: 380,
    right: 20,
    backgroundColor: '#222',
    borderRadius: 10,
    color: '#fff',
    paddingHorizontal: 10,
    marginHorizontal: 20,
    marginBottom: 20,
    fontFamily: 'Kan',
    letterSpacing: 1.2,
    borderWidth: 2,
    borderColor: "#555",
  },
  loadingText: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Kan',
    textAlign: 'center',
    marginTop: 20,
  },
  timeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 10,
    width: 400,
    left: 7,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 10,
    marginLeft: 80,
  },
  timeDigitsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 100,
  },
  timeDigitText: {
    color: '#fff',
    fontSize: 22,
    fontFamily: 'Kan',
  },
  header: {
    marginBottom: 20,
    width: 290,
    left: 62,
  },
  title: {
    fontSize: 28,
    color: '#fff',
    fontFamily: 'Pac',
    textAlign: 'center',
  },
  description: {
    fontSize: 15,
    color: '#ccc',
    fontFamily: 'Kan',
    textAlign: 'center',
    marginBottom: 53,
    lineHeight: 14,
  },
  mainContainer: {
    flex: 1,
    marginBottom: 15,
    backgroundColor: "#151515"
  },
  button: {
    width: 383,
    height: 70,
    backgroundColor: "#222",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 15,
    borderRadius: 15,
    position: "absolute",
    bottom: 90,
    left: 15.5,
    flexDirection: "row",
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Kan',
    letterSpacing: 1.2,
  },
});

export default CreateStyle;
