import { Dimensions, StyleSheet } from 'react-native';

const CreateStyle = StyleSheet.create({
  container: {
    alignItems: 'center',
    backgroundColor: '#f7f7f7',
    padding: 20,
    height: Dimensions.get('window').height * 1.1,
  },
  title: {
    fontSize: 36,
    marginBottom: 10,
    fontFamily: "Pac",
    color: '#fff',
  },
  header: {
    marginTop: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    paddingVertical: 10,
  },
  mapContainer: {
    padding: 5,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    marginTop: 20,
    borderRadius: 15,
    width: '104%',
    alignItems: 'center',
  },
  description: {
    fontSize: 16,
    color: '#fff',
    fontFamily: "Kan",
    textAlign: 'center',
    paddingHorizontal: 30,
    lineHeight: 18,
  },
  map: {
    width: Dimensions.get('window').width * 0.9359,
    height: 230,
    marginTop: 5,
  },
  input: {
    height: 40,
    borderColor: 'rgba(0, 0, 0, .7)',
    borderWidth: 1,
    marginVertical: 10,
    paddingHorizontal: 10,
    width: '89%',
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
  },
  loadingText: {
    fontSize: 18,
    color: '#fff',
    marginTop: 20,
    fontFamily: "Pac",
  },
  nextButton: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 150,
    alignItems: 'center',
    justifyContent: "space-between",
    marginTop: 10,
    padding: 7,
    paddingHorizontal: 19,
  },
  nextButtonText: {
    color: '#000',
    fontSize: 18,
    marginRight: 5,
    fontFamily: "Kan",
  },
  text: {
    fontFamily: "Kan",
    letterSpacing: 1,
    color: '#000', // Adjust text color for visibility
  },
  hr: {
    height: 18,
    width: 0,
    backgroundColor: "#000",
    marginHorizontal: 18,
    shadowColor: 'rgba(240, 240, 240, 1)',
    shadowOffset: { width: 8, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 0,
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: "flex-end",
    alignItems: "center",
    width: 300,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  submitButton: {
    backgroundColor: '#FF7E5F',
    padding: 8,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewPager: {
    flex: 1,
  },
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeContainer: { // New style for the time selection container
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 15,
    width: '100%',
    alignItems: 'center',
    marginTop: 20,
  },
  timeText: {
    fontSize: 20,
    fontFamily: 'Kan',
    marginBottom: 15,
    color: '#000',
  },
  timeInput: {
    height: 40,
    borderColor: 'rgba(0, 0, 0, .7)',
    borderWidth: 1,
    paddingHorizontal: 10,
    width: '90%',
    borderRadius: 10,
    marginBottom: 10,
  },
  timeSubmitButton: {
    backgroundColor: '#FF7E5F',
    padding: 10,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '90%',
  },
  timeSubmitButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  picker: {
    height: 50,
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 10,
    marginVertical: 10,
    paddingHorizontal: 10,
  },
  calendarButton: { // New style for calendar buttons
    backgroundColor: '#FF7E5F',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginVertical: 5,
  },
  calendarButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  timeDigitsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 20,
  },
  timeDigit: {
    width: 40,
    height: 50,
    backgroundColor: '#222',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 2,
  },
  timeDigitText: {
    color: '#fff',
    fontSize: 25,
    fontFamily: 'Kan',
  },
});

export default CreateStyle;
